version: "2.1"

volumes:
  x11:
  photos:

services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - "x11:/tmp/.X11-unix"
      - "photos:/photos"
    environment:
      - WIDTH=${WIDTH}
      - ALBUM_URL=${ALBUM_URL}
      - CRON=${CRON}
      - DELAY=${DELAY}
      - RELOAD_INTERVAL=${RELOAD_INTERVAL}
      - DOWNLOAD_LOCATION=/photos
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
      PORTAL_SSID: "Picture frame"
  # This was used to test the X server
  # glxgears:
  #   build: ./glxgears
  #   restart: always
  #   devices:
  #     - /dev/dri
  #   group_add:
  #     - video
  #   volumes:
  #     - "x11:/tmp/.X11-unix"
  xserver:
    # Replace <arch> with your own machines architecture. The default architecture without a - is `amd64`
    image: balenablocks/xserver
    restart: always
    privileged: true
    environment:
      - CURSOR=false
    volumes:
      - "x11:/tmp/.X11-unix"
